### ISSUE TITLE
(How) Config/Values are passed into Terraform on cluster update create

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/kubernetes-investigations#24]
## Background:

https://github.com/ministryofjustice/kubernetes-investigations/pull/22#discussion_r184671613

## To Be Specified

**Comment by alkar** [comment]
The only input to terraform currently is the workspace name, from which the cluster name is constructed. It is automatically determined by the files present under [kops/](../tree/master/kops/). A user can create a new cluster just by adding an appropriate file in this path.

I think we can close this issue, at least until the process changes in a way that requires more inputs from the user.

@kalbir @kerin @tatyree thoughts?
