### ISSUE TITLE
Every step in the cluster creation process should be doing one thing only based on inputs it receives from upstream

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/kubernetes-investigations#25]
## Details

Based on [this comment](https://github.com/ministryofjustice/kubernetes-investigations/pull/22#discussion_r184671613), we need to make some minor modifications to the way the cluster creation scripts work, based on best practices for CI pipelines.

There are three distinct top-level processes:
1. Terraform - update or create main AWS resources such as VPC, subnets, Route53, etc
2. Kops - update or create cluster
3. Helm/kubectl - update or create services on the cluster

Related to https://github.com/ministryofjustice/cloud-platform/issues/38

## Done when
- [ ] Every discrete step in the process is implemented by one or more independent scripts.
- [ ] Each script has inputs and outputs which can be used to bind the steps together in a CI pipeline. No script should be fetching its own inputs but they should be passed down to it (eg. CLI flags, stdin).
- [ ] There is a documentation page explaining the process to create a new cluster, with examples.
- [ ] These instructions have been read and tested for clarity and correctness by a third party (not the developer).

**Comment by AntonyBishop** [comment]
Close - out of date
